using TileTextureGenerator.Core.Enums;
using TileTextureGenerator.Core.Models;
using TileTextureGenerator.Core.Ports.Input;
using TileTextureGenerator.Core.Ports.Output;

namespace TileTextureGenerator.Core.Entities;

/// <summary>
/// Abstract base class for all transformation types.
/// Contains common properties and behavior shared by all transformations.
/// Implements ITransformationManager for self-management capabilities.
/// Does NOT contain serialization logic (handled by persistence layer).
/// </summary>
public abstract class TransformationBase : ITransformationManager
{
    private readonly ITransformationStore _store;
    private ProjectBase? _parentProject;
    private Guid? _id;
    private bool _initialized;
    private ImageData? _generatedTexture;

    /// <summary>
    /// Parent project that owns this transformation.
    /// Immutable after initialization.
    /// </summary>
    public ProjectBase ParentProject
    {
        get => _parentProject ?? throw new InvalidOperationException("Transformation not initialized. Call Initialize first.");
        private set
        {
            if (_initialized)
                throw new InvalidOperationException("Cannot modify parent project after initialization.");
            _parentProject = value;
        }
    }

    /// <summary>
    /// Result image generated by the transformation
    /// </summary>
    public ImageData? GeneratedTexture
    {
        get => _generatedTexture;
        private set => _generatedTexture = value;
    }

    /// <summary>
    /// Unique identifier of the transformation.
    /// Immutable after initialization.
    /// </summary>
    public Guid Id
    {
        get => _id ?? throw new InvalidOperationException("Transformation not initialized. Call Initialize first.");
        private set
        {
            if (_initialized)
                throw new InvalidOperationException("Cannot modify ID after initialization.");
            _id = value;
        }
    }

    /// <summary>
    /// Type identifier for polymorphic instantiation (typically the class name).
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Icon representing this transformation type in the UI (PNG format, typically 32x32 or 64x64).
    /// Must be overridden in concrete classes.
    /// </summary>
    public abstract ImageData? Icon { get; }

    /// <summary>
    /// Type of paper required for printing this transformation output.
    /// Default is Standard paper. Override in concrete classes for transformations requiring heavy cardstock.
    /// </summary>
    public virtual PaperType RequiredPaperType => PaperType.Standard;

    /// <summary>
    /// Collection of edge flap configurations for all four sides.
    /// Access configurations using EdgeFlap[ImageSide.Top], EdgeFlap[ImageSide.Right], etc.
    /// </summary>
    public EdgeFlapCollection EdgeFlap { get; } = new EdgeFlapCollection();

    /// <summary>
    /// Constructor with dependency injection.
    /// Store is injected by DI container.
    /// </summary>
    /// <param name="store">The transformation store for persistence operations.</param>
    protected TransformationBase(ITransformationStore store)
    {
        _store = store ?? throw new ArgumentNullException(nameof(store));
    }

    /// <summary>
    /// Initializes the transformation with its parent project and unique identifier.
    /// Must be called once after construction and before any other operations.
    /// </summary>
    /// <param name="parentProject">The project that owns this transformation.</param>
    /// <param name="id">Unique identifier for the transformation.</param>
    public void Initialize(ProjectBase parentProject, Guid id)
    {
        ArgumentNullException.ThrowIfNull(parentProject);

        if (_initialized)
            throw new InvalidOperationException("Transformation already initialized.");

        if (id == Guid.Empty)
            throw new ArgumentException("Transformation ID cannot be empty.", nameof(id));

        ParentProject = parentProject;
        Id = id;
        Type = GetType().Name;
        _initialized = true;
    }

    /// <inheritdoc />
    public async Task SaveChangesAsync()
    {
        if (!_initialized)
            throw new InvalidOperationException("Transformation not initialized. Call Initialize first.");

        await _store.SaveAsync(this);
    }

    /// <summary>
    /// Executes the transformation and generates the output image.
    /// </summary>
    /// <returns>The generated image as PNG.</returns>
    protected abstract Task<ImageData> ExecuteAsync();

    /// <inheritdoc />
    /// <summary>
    /// Generates the transformation output by executing the transformation logic,
    /// stores the result in GeneratedTexture property, and persists the changes.
    /// </summary>
    /// <returns>The generated image that can be used immediately by the caller.</returns>
    public async Task<ImageData> GenerateAsync()
    {
        if (!_initialized)
            throw new InvalidOperationException("Transformation not initialized. Call Initialize first.");
        var generated = await ExecuteAsync();
        _generatedTexture = generated;
        await SaveChangesAsync();
        return generated;
    }
}
